version: '3.7'
services:
 asesorias-microservicios:
  container_name: 'asesorias-microservicios'
  image: oscarmantilla/asesorias-microservicios:1.0
  build:
   context: .
  ports:
   - "5001:3001"
  networks:
   - asesorias
networks:
 asesorias: